name = "iraqnow"
pages_build_output_dir = "pages-deploy"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://afwbjyfnhchoqgqbqrfg.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_kLEM0R1eYNwEe9zZJrRL7A_E_Sh8CJh"
MEILISEARCH_HOST = "https://ms-7fba9866c156-55153.par.meilisearch.io"
NEXT_PUBLIC_APP_URL = "https://iraqnow.pages.dev"
NEXT_PUBLIC_APP_NAME = "IraqNow"
NEXTAUTH_URL = "https://iraqnow.pages.dev"
