name = "iraqnow"
pages_build_output_dir = "pages-deploy"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://afwbjyfnhchoqgqbqrfg.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_kLEM0R1eYNwEe9zZJrRL7A_E_Sh8CJh"
MEILISEARCH_HOST = "https://ms-7fba9866c156-55153.par.meilisearch.io"
MEILISEARCH_SEARCH_KEY = "43adf2d3612dd385beb287cbb8bf065255f1ab0da6cb413cfd0c5bd8fb4c87e5"
MEILISEARCH_MASTER_KEY = "227eed949d2020fb92f2d347d1338a1caf9fd680"
MEILISEARCH_ADMIN_KEY = "c35181225c36d63cd0790ae9f5e97cdf9f451ceac11c2ce0d5010390dbaacb2e"
NEXT_PUBLIC_APP_URL = "https://iraqnow.pages.dev"
NEXT_PUBLIC_APP_NAME = "IraqNow"
NEXTAUTH_URL = "https://iraqnow.pages.dev"
NEXTAUTH_SECRET = "iqn-9c4547f9065df884a3b7c2e1d8f6093e7a5b4c2d1e0f9876543210abcdef98765"
AUTH_SECRET = "iqn-9c4547f9065df884a3b7c2e1d8f6093e7a5b4c2d1e0f9876543210abcdef98765"

